### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by brand17** [imanoop7/Running-ollama-on-colab#1]
I am getting this error when try to run the notebook in colab
https://colab.research.google.com/drive/1RqLyHiADYV6EE-fdnkH07eUdEKiKcq32?usp=sharing

**Comment by brand17** [comment]
I think the following calls from Linux terminal should be documented:
`curl -fsSL https://ollama.com/install.sh | sh`
`ollama serve & ollama pull llama3`

**Comment by imanoop7** [comment]
> I am getting this error when try to run the notebook in colab https://colab.research.google.com/drive/1RqLyHiADYV6EE-fdnkH07eUdEKiKcq32?usp=sharing

don't have access to your colab notebook, if the issue still persist paste your issue here with all the details
